name: Send a Discord message when new RSS feeds update
on:
  rss:
    url: ${{ secrets.DCINSIDE_RSSFEED_GALLERY_RECOMMEND }}
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_GALLERY_RECOMMEND }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_RECOMMEND }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_RECOMMEND }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`디시인사이드 - 편두통 갤러리 - 개념글`'\n'**${{on.rss.outputs.title}}**'\n'${{on.rss.outputs.link}}"
