name: Actionsflow
on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:
    inputs:
      include:
        description: "--include: workflow file filter, you can use glob format to filter your workflows, the default value is empty value, means no filter will be using"
        required: false
        default: ""
      force:
        description: "--force: whether force to run workflow, true or false"
        required: false
        default: "false"
      verbose:
        description: "--verbose: debug workflow, true or false"
        required: false
        default: "false"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    concurrency: actionsflow
    steps:
      - uses: actions/checkout@v4
      
      # 최신 Node.js 버전 설치
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Actionsflow를 직접 설치 및 실행
      - name: Install Actionsflow
        run: npm install -g @actionsflow/cli

      - name: Run Actionsflow
        run: actionsflow build --include ${{ github.event.inputs.include || ''}} -f ${{github.event.inputs.force == 'true' && 'true' || 'false'}} --verbose ${{github.event.inputs.verbose == 'true' && 'true' || 'false'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 필요에 따라 추가 환경 변수를 여기에 설정

      # Act를 직접 설치 및 실행
      - name: Install and Setup Act
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
          curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash

      - name: Run Act
        run: act --workflows ./dist/workflows --secret-file ./dist/.secrets --eventpath ./dist/event.json --env-file ./dist/.env -P ubuntu-latest=actionsflow/act-environment:v1 -P ubuntu-18.04=actionsflow/act-environment:v1
